configuration: Debug
image: Visual Studio 2017

environment:
  MIK_TEX_INSTALL_DIR: 'C:\MikTex\'

version: '7.4.0.{build}'

assembly_info:
  patch: true
  file: SolutionInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"  

clone_depth: 1

cache:
  packages -> **\packages.config  

install:
- set PATH=C:\Ruby22\bin;C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- cmd: git submodule update --init --recursive
- ps: >-
    (new-object net.webclient).DownloadFile('https://download.microsoft.com/download/A/2/D/A2D8587D-0027-4217-9DAD-38AFDB0A177E/msxml.msi', 'C:\\msxml.msi')

    Start-Process msiexec.exe -ArgumentList /i, C:\msxml.msi, /quiet, /qn, /norestart -Wait

- ps: >-
    (new-object net.webclient).DownloadFile('https://github.com/Open-Systems-Pharmacology/MiKTeX/releases/download/v2.9.3/MikTex.2.9.3.msi', 'C:\\MikTex.msi')

    Start-Process msiexec.exe -ArgumentList /i, C:\MikTex.msi, /quiet, /qn, /norestart, INSTALLDIR=$env:MIK_TEX_INSTALL_DIR -Wait

before_build:
  - nuget sources add -name bddhelper -source https://ci.appveyor.com/nuget/ospsuite-bddhelper 
  - nuget sources add -name utility -source https://ci.appveyor.com/nuget/ospsuite-utility 
  - nuget sources add -name serializer -source https://ci.appveyor.com/nuget/ospsuite-serializer
  - nuget sources add -name texreporting -source https://ci.appveyor.com/nuget/ospsuite-texreporting  
  - nuget sources add -name databinding -source https://ci.appveyor.com/nuget/ospsuite-databinding 
  - nuget sources add -name databinding-devexpress -source https://ci.appveyor.com/nuget/ospsuite-databinding-devexpress 
  - nuget sources add -name funcparser -source https://ci.appveyor.com/nuget/ospsuite-funcparser 
  - nuget sources add -name simmodel -source https://ci.appveyor.com/nuget/ospsuite-simmodel
  - nuget sources add -name cvodes -source https://ci.appveyor.com/nuget/ospsuite-simmodel-solver-cvodes-282
  - nuget sources add -name core -source https://ci.appveyor.com/nuget/ospsuite-core
  - nuget restore

build:
  verbosity: minimal
  project: PKSim.sln

notifications:
  - provider: Slack
    incoming_webhook:      
      secure: 4MH9Em6TtrKalq6808dhPOqypTfYBJvVlqPaa9akNyF1h7st5qNdNezFp6T+bWXqrcZ4q/smtPcJ7LkUFHL46JDYUFlIL8FDz+ApX/vP+x0=

test_script:
  - rake cover