name: Build Nightly 13.0
run-name: Version 13.0.${{ github.run_number }}

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Validate source branch
      run: |
        if [ "${{ github.ref_name }}" != "V13" ]; then
          echo "::error::Please call the workflow from the V13 branch"
          exit 1
        fi