name: Build and Publish V13
run-name: Version 13.0.${{ github.run_number }} (${{ github.event.head_commit.message }})

on:
  push:
    branches:
    - develop

permissions:
  packages: write

jobs:
  build-test-publish:
    runs-on: ${{ vars.GHA_DEFAULT_RUNNER_WINDOWS || 'windows-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: 'true'

      - name: Add GitHub feed
        run: |
          nuget sources add -username Open-Systems-Pharmacology -password ${{ secrets.GITHUB_TOKEN }} -name OSP-GitHub-Packages -source "https://nuget.pkg.github.com/Open-Systems-Pharmacology/index.json"

      - name: define env variables
        run: |
          echo "APP_VERSION=13.0.${{ github.run_number }}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Build
        env:
          DevExpress_License: ${{ secrets.DEV_EXPRESS_KEY }}
        run: dotnet build PKSim.sln -p:Version=${{env.APP_VERSION}} -p:ExcludeDesigner=true

      - name : Test
        run: dotnet test PKSim.sln -v normal --no-build  --logger:"html;LogFileName=testLog_Windows.html"

      - name: Pack the project
        run: dotnet pack .\PKSim.sln --no-build --no-restore -o ./ -p:PackageVersion=${{env.APP_VERSION}} --configuration=Debug

      - name: Push test log as artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: testLog_Windows
          path: ./**/testLog*.html

      - name: Publish to GitHub registry
        run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
